[project]
name = "neural-networks"
version = "0.1.0"
description = "25/26 University of Wroclaw class"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipywidgets>=8.1.8",
    "matplotlib>=3.10.8",
    "numpy>=2.4.2",
    "pandas>=3.0.1",
    "pillow>=12.1.1",
    "torch>=2.10.0",
    "torchvision>=0.25.0",
    "tqdm>=4.67.3",
]

[dependency-groups]
dev = [
    "ipykernel>=7.2.0",
    "jupyterlab>=4.5.5",
    "pre-commit>=4.5.1",
    "ruff>=0.15.4",
]

[tool.uv]
package = true

[tool.ruff]
target-version = "py313"

[tool.ruff.format]


[tool.ruff.lint]
select = ["E", "F", "UP", "B", "SIM", "I"]
